PLEASE NOTE THAT C-INTERCAL FAILS TO RECOGNIZE THE SECOND ABSTAIN STATEMENT
DO % 5 0 ABSTAIN FROM (00010)
DO % 5 0 REINSTATE (00010)
DO . 1 1 <- # 1 0
0 9
(1 0) PLEASE NO TAB STAIN FROM READING OUT
DO READ OUT .011
DO GIVE UP
DOES THIS DO ANYTHING?  THANK YOU
