DGOLC: DGOLC.hs AST/AST.hs AST/Parse.hs CodeGen/CodeGen.hs CodeGen/DGOLLibs.hs CodeGen/Runtime.hs CodeGen/Types.hs CodeGen/Util.hs
	ghc --make DGOLC

clean:
	$(RM) DGOLC *.hi *.o AST/*.hi AST/*.o CodeGen/*.hi CodeGen/*.o

.PHONY: clean
